# Generated by Django 4.0.3 on 2022-03-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_category_nomination_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='category',
            new_name='category_id',
        ),
    ]
