# Generated by Django 4.0.3 on 2022-03-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_remove_user_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='category_id',
            new_name='category',
        ),
    ]
