# Generated by Django 4.0.3 on 2022-03-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_remove_nomination_email_remove_vote_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
