# Generated by Django 4.0.3 on 2022-03-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_alter_vote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='request_obj',
            field=models.TextField(blank=True, null=True),
        ),
    ]
