# Generated by Django 4.0.3 on 2022-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_alter_nomination_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
