# Generated by Django 4.0.3 on 2022-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_category_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ipaddress',
        ),
        migrations.AddField(
            model_name='vote',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
